// Given two strings s and t which consist of only lowercase letters.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Find the letter that was added in t.
//
// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.


/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function (s, t) {
    let map = {};
    for (let i = s.length - 1; i >= 0; i--) {
        map[s[i]] = map[s[i]] + 1 || 1;
        map[t[i]] = map[t[i]] + 1 || 1;
    }
    map[t[t.length - 1]] = map[t[t.length - 1]] + 1 || 1;

    for (let item in map) {
        if (map[item] % 2 === 1) {
            return item;
        }
    }
};

var findTheDifference2 = function (s, t) {
    let charCode = t.charCodeAt(s.length);

    // Iterate through both strings and char codes
    for (let i = 0; i < s.length; i++) {
        charCode -= s.charCodeAt(i);
        charCode += t.charCodeAt(i);
    }
    return String.fromCharCode(charCode);
};

console.log(findTheDifference2('whw34', 'whlw34'));
